const Data = [
  {
    cardicon: "Pc.png",
    Devicenname: "PC-23243",
    name: "Assembledi7",
    processor: "intel i7,8GB RAM,300GB HDD",
    assignedTo: "",
    iswarning: true,
    isRented: true,
    isSelected: false,
  },
  {
    cardicon: "Macbook.png",
    Devicenname: "LAP:0025",
    name: "Macbook 2017",
    processor: "intel  i5,8GB RAM,300GB HDD",
    assignedTo: "IndianOil Instance J231",
    iswarning: false,
    isRented: false,
    isSelected: false,
  },
  {
    Devicenname: "SRV:0325",
    cardicon: "Red.png",
    name: "AWS Red Hat",
    processor: "intel i9,64GB RAM,2TB HDD",
    assignedto: "",
    iswarning: false,
    isRented: false,
    isSelected: false,
  },
  {
    cardicon: "Belkin.png",
    Devicenname: "RTR:0325",
    name: "Belkin 3500Gi",
    processor: "intel i7,8gb Ram,300gb Hdd",
    assignedto: "",
    iswarning: false,
    isRented: false,
    isSelected: false,
  },
  {
    cardicon: "Fingerprint.png",
    Devicenname: "BIO:2645",
    name: "Fingerprint Scanner i300",
    processor: "Zebronics",
    assignedto: "",
    iswarning: false,
    isRented: false,
    isSelected: false,
  },
  {
    Devicenname: "DRV-2645",
    cardicon: "pendrive.png",
    name: "16GB USB 2.0",
    processor: "HP",
    assignedTo: "",
    iswarning: false,
    isRented: true,
    isSelected: false,
  },
  {
    cardicon: "mobile.png",
    Devicenname: "MOB:2645",
    name: "Sansung M20",
    processor: "Samsung 16GB",
    assignedto: "",
    iswarning: false,
    isRented: false,
    isSelected: true,
  },
  {
    cardicon: "iris.png",
    Devicenname: "IS:0325",
    name: "Iris Scanner",
    processor: "Logitech",
    assignedTo: "",
    iswarning: false,
    isRented: false,
    isSelected: false,
  },
  {
    Devicenname: "DTC-0325",
    cardicon: "sandisk.png",
    name: "Sandisk 64GB",
    processor: "Sandisk",
    assignedTo: "",
    iswarning: false,
    isRented: false,
    isSelected: false,
  },
  {
    cardicon: "Network.png",
    Devicenname: "NS-2645",
    name: "Network Switch",
    processor: "Cisco",
    assignedto: "",
    iswarning: false,
    isRented: false,
    isSelected: false,
  },
  {
    cardicon: "Web.png",
    Devicenname: "WC:2645",
    name: "Webcam LOG23",
    processor: "Logitech",
    assignedTo: "",
    iswarning: true,
    isRented: true,
    isSelected: false,
  },
  {
    Devicenname: "WC-2645",
    cardicon: "Tablet.png",
    name: "Tablets",
    processor: "Logitech",
    assignedTo: "",
    iswarning: true,
    isRented: true,
    isSelected: false,
  },
];

export default Data;
